services:
  - type: web
    name: signova
    env: python
    plan: free
    region: frankfurt # or oregon, pick closest
    scaling:
      minInstances: 1
      maxInstances: 1
    buildCommand: pip install -r requirements_web.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn signova.wsgi:application --timeout 180 --workers 1 --preload --max-requests 1000 --max-requests-jitter 50
    healthCheckPath: /health/
    autoDeploy: true
    envVars:
      - key: WEB_CONCURRENCY
        value: 1
      - key: PYTHON_UNBUFFERED
        value: true
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: MALLOC_TRIM_THRESHOLD_
        value: 65536

      - key: DJANGO_SETTINGS_MODULE
        value: signova.settings
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: signova_db
          property: connectionString

databases:
  - name: signova_db
    databaseName: signova
    user: signova_user
